### ISSUE TITLE
THIS IS RANSOMEWARE !!!

### ISSUE THREAD

**Issue by ghost** [Modify24x7/BlueStacks5RT#1]
DO NOT USE THIS !!!!!!!!!
MSIL/Packed.DotNetGuard.A, this will most likely Encrypt your Data and ask for Money.

**Comment by Modify24x7** [comment]
OK.
Pack with StrongVM, Donate for unlocking xposed.
Any proof damage your system, submit.

Best Regards,
Gorav Gupta
